#pragma once
#include <string>

enum class TokenType {
  LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
  SEMICOLON, COMMA, DOT,
  PLUS, MINUS, STAR, SLASH, PERCENT,
  PLUS_EQ, MINUS_EQ, STAR_EQ, SLASH_EQ, PERCENT_EQ,
  EQ, EQ_EQ, BANG, BANG_EQ,
  LT, LT_EQ, GT, GT_EQ,
  IDENTIFIER, STRING, NUMBER,
  VAR, PRINT, PRINT_NL, IF, ELSE, WHILE, FOR, FUN, RETURN,
  BREAK, CONTINUE, IN,
  UNLESS, LOOP,
  TRUE, FALSE, NIL,
  AND, OR,
  QUESTION, COLON, ARROW,
  IS, ISNT,
  TRY, CATCH, FINALLY, THROW,
  IMPORT,
  CONST,
  EOF_
};

struct Token {
  TokenType type;
  std::string value;
  int line;
};
